apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectspringboot
spec:
  selector:
    matchLabels:
      app: projectspringboot
  replicas: 2
  template:
    metadata:
      labels:
        app: projectspringboot
    spec:
      containers:
      - name: projectspringboot
        image: thiernos/projectspringboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http



