apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectspringboot
spec:
  selector:
    matchLabels:
      app: projectspringboot
  replicas: 2
  template:
    metadata:
      labels:
        app: projectspringboot
    spec:
      containers:
      - name: projectspringboot
        image: thiernos/projectspringboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: jobapplication-svc
spec:
  selector:
    app: projectspringboot
  ports:
  - name: http
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
